[project]
name = "extension-meilisearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marko>=2.1.3",
    "meilisearch>=0.34.1",
    "python-frontmatter>=1.1.0",
    "pyyaml>=6.0.2",
    "toml>=0.10.2",
]
